config/routes.rb
Rails.application.routes.draw do
  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
  accepts_nested_attributes_for :tasks, reject_if: :all_blank, allow_destroy: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    @project.tasks.build
  end

  # GET /projects/1/edit
  def edit
    @project.tasks.build
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, tasks_attributes: [:id, :description, :done, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Debugcocoon
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/projects/_form.html.haml
= form_for(project) do |f|
  - if project.errors.any?
    #error_explanation
      %h2
        = pluralize(project.errors.count, "error")
        prohibited this project from being saved:
      %ul
        - project.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  %h3 Tasks
  #tasks
    = f.fields_for :tasks do |task|
      = render 'task_fields', f: task
      .links
        = link_to_add_association 'add task', f, :tasks
  .actions
    = f.submit

app/views/projects/_task_fields.html.haml
.nested-fields
  .field
    = f.label :description
    %br/
    = f.text_field :description
    .field
      = f.check_box :done
      = f.label :done
    = link_to_remove_association "remove task", f

app/views/projects/edit.html.haml
%h1 Editing Project
= render 'form', project: @project
= link_to 'Show', @project
|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
%p#notice= notice
%h1 Projects
%table
  %thead
    %tr
      %th Name
      %th Description
      %th{:colspan => "3"}
  %tbody
    - @projects.each do |project|
      %tr
        %td= project.name
        %td= project.description
        %td= link_to 'Show', project
        %td= link_to 'Edit', edit_project_path(project)
        %td= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Project', new_project_path

app/views/projects/new.html.haml
%h1 New Project
= render 'form', project: @project
= link_to 'Back', projects_path

app/views/projects/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @project.name
%p
  %strong Description:
  = @project.description
= link_to 'Edit', edit_project_path(@project)
|
= link_to 'Back', projects_path